Repository E-AN-study/E-AN, pull requests merged in 2024-01, with the labels that each got.

#5 [임주민] Feat: ChapterList 페이지 기능 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Messages.svg
  src/pages/ChapterListPage/ChapterCard.jsx
  src/pages/ChapterListPage/ChapterCard.scss
  src/pages/ChapterListPage/ChapterList.jsx
  src/pages/ChapterListPage/ChapterList.module.scss
  src/pages/ChapterListPage/index.jsx
  src/pages/ChapterListPage/index.module.scss
  src/styles/main.scss
Labels: bug

#7 [임주민] Header 컴포넌트 기능 구현
  src/pages/ChapterListPage/ChapterCard.jsx
  src/pages/ChapterListPage/ChapterCard.scss
  src/pages/ChapterListPage/Header.jsx
  src/pages/ChapterListPage/Header.scss
  src/pages/ChapterListPage/index.jsx
  src/pages/ChapterListPage/index.module.scss
  src/styles/main.scss
Labels: documentation

#11 [임주민] Feat: ChapterCard 컴포넌트 작성된 글 기능 추가
  .env
  .gitignore
  index.html
  package-lock.json
  src/App.jsx
  src/assets/images/E-AN-logo.png
  src/assets/images/cat-image.svg
  src/assets/images/light-img.png
  src/pages/ChapterListPage/ChapterCard.css
  src/pages/ChapterListPage/ChapterCard.css.map
  src/pages/ChapterListPage/ChapterCard.jsx
  src/pages/ChapterListPage/ChapterCard.scss
  src/pages/ChapterListPage/ChapterList.module.css
  src/pages/ChapterListPage/ChapterList.module.css.map
  src/pages/ChapterListPage/ChapterList.module.scss
  src/pages/ChapterListPage/index.module.css
  src/pages/ChapterListPage/index.module.css.map
  src/pages/ChapterListPage/index.module.scss
  src/pages/Test/Test.module.scss
  src/pages/TextList/TextList.jsx
  src/pages/main/MainLogo.jsx
  src/pages/main/MainLogo.module.scss
  src/pages/main/index.jsx
  src/utils/shareKaKaoLink.js
Labels: bug, ㅎㅇ

#12 feat : edit페이지 post와 이미지 선택기능
  .env
  .gitignore
  src/App.jsx
  src/assets/W148534016154950199.gif
  src/assets/profile1.jpg
  src/assets/profile2.jpg
  src/components/TextCard/TextCard.jsx
  src/pages/edit/edit.module.scss
  src/pages/edit/index.jsx
  src/utils/formatDateYMD.js
Labels: good first issue, help wanted
